export const BLIND_75 = [
    { title: "Two Sum", difficulty: "Easy", url: "https://leetcode.com/problems/two-sum/", topic_tags: ["Array"] },
    { title: "Best Time to Buy and Sell Stock", difficulty: "Easy", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", topic_tags: ["Array"] },
    { title: "Contains Duplicate", difficulty: "Easy", url: "https://leetcode.com/problems/contains-duplicate/", topic_tags: ["Array"] },
    { title: "Product of Array Except Self", difficulty: "Medium", url: "https://leetcode.com/problems/product-of-array-except-self/", topic_tags: ["Array"] },
    { title: "Maximum Subarray", difficulty: "Medium", url: "https://leetcode.com/problems/maximum-subarray/", topic_tags: ["Array"] },
    { title: "Maximum Product Subarray", difficulty: "Medium", url: "https://leetcode.com/problems/maximum-product-subarray/", topic_tags: ["Array"] },
    { title: "Search in Rotated Sorted Array", difficulty: "Medium", url: "https://leetcode.com/problems/search-in-rotated-sorted-array/", topic_tags: ["Array"] },
    { title: "Find Minimum in Rotated Sorted Array", difficulty: "Medium", url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/", topic_tags: ["Array"] },
    { title: "3Sum", difficulty: "Medium", url: "https://leetcode.com/problems/3sum/", topic_tags: ["Two Pointers"] },
    { title: "Container With Most Water", difficulty: "Medium", url: "https://leetcode.com/problems/container-with-most-water/", topic_tags: ["Two Pointers"] },
    { title: "Sum of Two Integers", difficulty: "Medium", url: "https://leetcode.com/problems/sum-of-two-integers/", topic_tags: ["Bit Manipulation"] },
    { title: "Number of 1 Bits", difficulty: "Easy", url: "https://leetcode.com/problems/number-of-1-bits/", topic_tags: ["Bit Manipulation"] },
    { title: "Counting Bits", difficulty: "Easy", url: "https://leetcode.com/problems/counting-bits/", topic_tags: ["Bit Manipulation"] },
    { title: "Missing Number", difficulty: "Easy", url: "https://leetcode.com/problems/missing-number/", topic_tags: ["Bit Manipulation"] },
    { title: "Reverse Bits", difficulty: "Easy", url: "https://leetcode.com/problems/reverse-bits/", topic_tags: ["Bit Manipulation"] },
    { title: "Climbing Stairs", difficulty: "Easy", url: "https://leetcode.com/problems/climbing-stairs/", topic_tags: ["Dynamic Programming"] },
    { title: "Coin Change", difficulty: "Medium", url: "https://leetcode.com/problems/coin-change/", topic_tags: ["Dynamic Programming"] },
    { title: "Longest Increasing Subsequence", difficulty: "Medium", url: "https://leetcode.com/problems/longest-increasing-subsequence/", topic_tags: ["Dynamic Programming"] },
    { title: "Longest Common Subsequence", difficulty: "Medium", url: "https://leetcode.com/problems/longest-common-subsequence/", topic_tags: ["Dynamic Programming"] },
    { title: "Word Break Problem", difficulty: "Medium", url: "https://leetcode.com/problems/word-break/", topic_tags: ["Dynamic Programming"] },
    { title: "Combination Sum", difficulty: "Medium", url: "https://leetcode.com/problems/combination-sum/", topic_tags: ["Dynamic Programming"] },
    { title: "House Robber", difficulty: "Medium", url: "https://leetcode.com/problems/house-robber/", topic_tags: ["Dynamic Programming"] },
    { title: "House Robber II", difficulty: "Medium", url: "https://leetcode.com/problems/house-robber-ii/", topic_tags: ["Dynamic Programming"] },
    { title: "Decode Ways", difficulty: "Medium", url: "https://leetcode.com/problems/decode-ways/", topic_tags: ["Dynamic Programming"] },
    { title: "Unique Paths", difficulty: "Medium", url: "https://leetcode.com/problems/unique-paths/", topic_tags: ["Dynamic Programming"] },
    { title: "Jump Game", difficulty: "Medium", url: "https://leetcode.com/problems/jump-game/", topic_tags: ["Dynamic Programming"] },
    { title: "Clone Graph", difficulty: "Medium", url: "https://leetcode.com/problems/clone-graph/", topic_tags: ["Graph"] },
    { title: "Course Schedule", difficulty: "Medium", url: "https://leetcode.com/problems/course-schedule/", topic_tags: ["Graph"] },
    { title: "Pacific Atlantic Water Flow", difficulty: "Medium", url: "https://leetcode.com/problems/pacific-atlantic-water-flow/", topic_tags: ["Graph"] },
    { title: "Number of Islands", difficulty: "Medium", url: "https://leetcode.com/problems/number-of-islands/", topic_tags: ["Graph"] },
    { title: "Longest Consecutive Sequence", difficulty: "Medium", url: "https://leetcode.com/problems/longest-consecutive-sequence/", topic_tags: ["Graph"] },
    { title: "Alien Dictionary", difficulty: "Hard", url: "https://leetcode.com/problems/alien-dictionary/", topic_tags: ["Graph"] },
    { title: "Graph Valid Tree", difficulty: "Medium", url: "https://leetcode.com/problems/graph-valid-tree/", topic_tags: ["Graph"] },
    { title: "Number of Connected Components in an Undirected Graph", difficulty: "Medium", url: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/", topic_tags: ["Graph"] },
    { title: "Insert Interval", difficulty: "Medium", url: "https://leetcode.com/problems/insert-interval/", topic_tags: ["Interval"] },
    { title: "Merge Intervals", difficulty: "Medium", url: "https://leetcode.com/problems/merge-intervals/", topic_tags: ["Interval"] },
    { title: "Non-overlapping Intervals", difficulty: "Medium", url: "https://leetcode.com/problems/non-overlapping-intervals/", topic_tags: ["Interval"] },
    { title: "Meeting Rooms", difficulty: "Easy", url: "https://leetcode.com/problems/meeting-rooms/", topic_tags: ["Interval"] },
    { title: "Meeting Rooms II", difficulty: "Medium", url: "https://leetcode.com/problems/meeting-rooms-ii/", topic_tags: ["Interval"] },
    { title: "Reverse a Linked List", difficulty: "Easy", url: "https://leetcode.com/problems/reverse-linked-list/", topic_tags: ["Linked List"] },
    { title: "Detect Cycle in a Linked List", difficulty: "Easy", url: "https://leetcode.com/problems/linked-list-cycle/", topic_tags: ["Linked List"] },
    { title: "Merge Two Sorted Lists", difficulty: "Easy", url: "https://leetcode.com/problems/merge-two-sorted-lists/", topic_tags: ["Linked List"] },
    { title: "Merge K Sorted Lists", difficulty: "Hard", url: "https://leetcode.com/problems/merge-k-sorted-lists/", topic_tags: ["Linked List"] },
    { title: "Remove Nth Node From End Of List", difficulty: "Medium", url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", topic_tags: ["Linked List"] },
    { title: "Reorder List", difficulty: "Medium", url: "https://leetcode.com/problems/reorder-list/", topic_tags: ["Linked List"] },
    { title: "Set Matrix Zeroes", difficulty: "Medium", url: "https://leetcode.com/problems/set-matrix-zeroes/", topic_tags: ["Matrix"] },
    { title: "Spiral Matrix", difficulty: "Medium", url: "https://leetcode.com/problems/spiral-matrix/", topic_tags: ["Matrix"] },
    { title: "Rotate Image", difficulty: "Medium", url: "https://leetcode.com/problems/rotate-image/", topic_tags: ["Matrix"] },
    { title: "Word Search", difficulty: "Medium", url: "https://leetcode.com/problems/word-search/", topic_tags: ["Matrix"] },
    { title: "Longest Substring Without Repeating Characters", difficulty: "Medium", url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/", topic_tags: ["String"] },
    { title: "Longest Repeating Character Replacement", difficulty: "Medium", url: "https://leetcode.com/problems/longest-repeating-character-replacement/", topic_tags: ["String"] },
    { title: "Minimum Window Substring", difficulty: "Hard", url: "https://leetcode.com/problems/minimum-window-substring/", topic_tags: ["String"] },
    { title: "Valid Anagram", difficulty: "Easy", url: "https://leetcode.com/problems/valid-anagram/", topic_tags: ["String"] },
    { title: "Group Anagrams", difficulty: "Medium", url: "https://leetcode.com/problems/group-anagrams/", topic_tags: ["String"] },
    { title: "Valid Parentheses", difficulty: "Easy", url: "https://leetcode.com/problems/valid-parentheses/", topic_tags: ["String"] },
    { title: "Valid Palindrome", difficulty: "Easy", url: "https://leetcode.com/problems/valid-palindrome/", topic_tags: ["String"] },
    { title: "Longest Palindromic Substring", difficulty: "Medium", url: "https://leetcode.com/problems/longest-palindromic-substring/", topic_tags: ["String"] },
    { title: "Palindromic Substrings", difficulty: "Medium", url: "https://leetcode.com/problems/palindromic-substrings/", topic_tags: ["String"] },
    { title: "Encode and Decode Strings", difficulty: "Medium", url: "https://leetcode.com/problems/encode-and-decode-strings/", topic_tags: ["String"] },
    { title: "Maximum Depth of Binary Tree", difficulty: "Easy", url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/", topic_tags: ["Tree"] },
    { title: "Same Tree", difficulty: "Easy", url: "https://leetcode.com/problems/same-tree/", topic_tags: ["Tree"] },
    { title: "Invert/Flip Binary Tree", difficulty: "Easy", url: "https://leetcode.com/problems/invert-binary-tree/", topic_tags: ["Tree"] },
    { title: "Binary Tree Maximum Path Sum", difficulty: "Hard", url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/", topic_tags: ["Tree"] },
    { title: "Binary Tree Level Order Traversal", difficulty: "Medium", url: "https://leetcode.com/problems/binary-tree-level-order-traversal/", topic_tags: ["Tree"] },
    { title: "Serialize and Deserialize Binary Tree", difficulty: "Hard", url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", topic_tags: ["Tree"] },
    { title: "Subtree of Another Tree", difficulty: "Easy", url: "https://leetcode.com/problems/subtree-of-another-tree/", topic_tags: ["Tree"] },
    { title: "Construct Binary Tree from Preorder and Inorder Traversal", difficulty: "Medium", url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/", topic_tags: ["Tree"] },
    { title: "Lowest Common Ancestor of BST", difficulty: "Easy", url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", topic_tags: ["Tree"] },
    { title: "Validate Binary Search Tree", difficulty: "Medium", url: "https://leetcode.com/problems/validate-binary-search-tree/", topic_tags: ["Tree"] },
    { title: "Kth Smallest Element in a BST", difficulty: "Medium", url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", topic_tags: ["Tree"] },
    { title: "Implement Trie (Prefix Tree)", difficulty: "Medium", url: "https://leetcode.com/problems/implement-trie-prefix-tree/", topic_tags: ["Trie"] },
    { title: "Add and Search Word", difficulty: "Medium", url: "https://leetcode.com/problems/design-add-and-search-words-data-structure/", topic_tags: ["Trie"] },
    { title: "Word Search II", difficulty: "Hard", url: "https://leetcode.com/problems/word-search-ii/", topic_tags: ["Trie"] },
    { title: "Merge K Sorted Lists", difficulty: "Hard", url: "https://leetcode.com/problems/merge-k-sorted-lists/", topic_tags: ["Heap"] },
    { title: "Top K Frequent Elements", difficulty: "Medium", url: "https://leetcode.com/problems/top-k-frequent-elements/", topic_tags: ["Heap"] },
    { title: "Find Median from Data Stream", difficulty: "Hard", url: "https://leetcode.com/problems/find-median-from-data-stream/", topic_tags: ["Heap"] }
];

export const STRIVER_SDE = [
    { title: "Set Matrix Zeroes", difficulty: "Medium", url: "https://leetcode.com/problems/set-matrix-zeroes/", topic_tags: ["Arrays"] },
    { title: "Pascal's Triangle I", difficulty: "Easy", url: "https://leetcode.com/problems/pascals-triangle/", topic_tags: ["Arrays"] },
    { title: "Next Permutation", difficulty: "Medium", url: "https://leetcode.com/problems/next-permutation/", topic_tags: ["Arrays"] },
    { title: "Kadane's Algorithm", difficulty: "Medium", url: "https://leetcode.com/problems/maximum-subarray/", topic_tags: ["Arrays"] },
    { title: "Sort an array of 0's 1's and 2's", difficulty: "Medium", url: "https://leetcode.com/problems/sort-colors/", topic_tags: ["Arrays"] },
    { title: "Stock Buy and Sell", difficulty: "Easy", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", topic_tags: ["Arrays"] },
    { title: "Rotate matrix by 90 degrees", difficulty: "Medium", url: "https://leetcode.com/problems/rotate-image/", topic_tags: ["Arrays Part-II"] },
    { title: "Merge Overlapping Subintervals", difficulty: "Medium", url: "https://leetcode.com/problems/merge-intervals/", topic_tags: ["Arrays Part-II"] },
    { title: "Merge two sorted arrays without extra space", difficulty: "Easy", url: "https://leetcode.com/problems/merge-sorted-array/", topic_tags: ["Arrays Part-II"] },
    { title: "Find the Duplicate Number", difficulty: "Medium", url: "https://leetcode.com/problems/find-the-duplicate-number/", topic_tags: ["Arrays Part-II"] },
    { title: "Search in a 2D matrix", difficulty: "Medium", url: "https://leetcode.com/problems/search-a-2d-matrix/", topic_tags: ["Arrays Part-III"] },
    { title: "Pow(x, n)", difficulty: "Medium", url: "https://leetcode.com/problems/powx-n/", topic_tags: ["Arrays Part-III"] },
    { title: "Majority Element-I", difficulty: "Easy", url: "https://leetcode.com/problems/majority-element/", topic_tags: ["Arrays Part-III"] },
    { title: "Majority Element-II", difficulty: "Medium", url: "https://leetcode.com/problems/majority-element-ii/", topic_tags: ["Arrays Part-III"] },
    { title: "Grid unique paths", difficulty: "Medium", url: "https://leetcode.com/problems/unique-paths/", topic_tags: ["Arrays Part-III"] },
    { title: "Reverse Pairs", difficulty: "Hard", url: "https://leetcode.com/problems/reverse-pairs/", topic_tags: ["Arrays Part-III"] },
    { title: "Two Sum", difficulty: "Easy", url: "https://leetcode.com/problems/two-sum/", topic_tags: ["Arrays Part-IV"] },
    { title: "4 Sum", difficulty: "Medium", url: "https://leetcode.com/problems/4sum/", topic_tags: ["Arrays Part-IV"] },
    { title: "Longest Consecutive Sequence", difficulty: "Medium", url: "https://leetcode.com/problems/longest-consecutive-sequence/", topic_tags: ["Arrays Part-IV"] },
    { title: "Longest Substring Without Repeating Characters", difficulty: "Medium", url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/", topic_tags: ["Arrays Part-IV"] },
    { title: "Reverse a LL", difficulty: "Easy", url: "https://leetcode.com/problems/reverse-linked-list/", topic_tags: ["Linked List"] },
    { title: "Find Middle of Linked List", difficulty: "Easy", url: "https://leetcode.com/problems/middle-of-the-linked-list/", topic_tags: ["Linked List"] },
    { title: "Merge two Sorted Lists", difficulty: "Easy", url: "https://leetcode.com/problems/merge-two-sorted-lists/", topic_tags: ["Linked List"] },
    { title: "Remove Nth node from end of LL", difficulty: "Medium", url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", topic_tags: ["Linked List"] },
    { title: "Add two numbers as LinkedList", difficulty: "Medium", url: "https://leetcode.com/problems/add-two-numbers/", topic_tags: ["Linked List"] },
    { title: "Delete Node in a Linked List", difficulty: "Easy", url: "https://leetcode.com/problems/delete-node-in-a-linked-list/", topic_tags: ["Linked List"] },
    { title: "Intersection of two LL", difficulty: "Easy", url: "https://leetcode.com/problems/intersection-of-two-linked-lists/", topic_tags: ["Linked List Part-II"] },
    { title: "Detect a loop in LL", difficulty: "Easy", url: "https://leetcode.com/problems/linked-list-cycle/", topic_tags: ["Linked List Part-II"] },
    { title: "Reverse LL in group of K", difficulty: "Hard", url: "https://leetcode.com/problems/reverse-nodes-in-k-group/", topic_tags: ["Linked List Part-II"] },
    { title: "Check if LL is palindrome", difficulty: "Easy", url: "https://leetcode.com/problems/palindrome-linked-list/", topic_tags: ["Linked List Part-II"] },
    { title: "Find starting point of loop", difficulty: "Medium", url: "https://leetcode.com/problems/linked-list-cycle-ii/", topic_tags: ["Linked List Part-II"] },
    { title: "Rotate a LL", difficulty: "Medium", url: "https://leetcode.com/problems/rotate-list/", topic_tags: ["Linked List and Arrays"] },
    { title: "Clone a LL with random pointer", difficulty: "Medium", url: "https://leetcode.com/problems/copy-list-with-random-pointer/", topic_tags: ["Linked List and Arrays"] },
    { title: "3 Sum", difficulty: "Medium", url: "https://leetcode.com/problems/3sum/", topic_tags: ["Linked List and Arrays"] },
    { title: "Trapping Rainwater", difficulty: "Hard", url: "https://leetcode.com/problems/trapping-rain-water/", topic_tags: ["Linked List and Arrays"] },
    { title: "Remove duplicates from sorted array", difficulty: "Easy", url: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/", topic_tags: ["Linked List and Arrays"] },
    { title: "Max Consecutive Ones", difficulty: "Easy", url: "https://leetcode.com/problems/max-consecutive-ones/", topic_tags: ["Linked List and Arrays"] },
    { title: "Minimum coins", difficulty: "Medium", url: "https://leetcode.com/problems/coin-change/", topic_tags: ["Greedy Algorithm"] },
    { title: "Assign Cookies", difficulty: "Easy", url: "https://leetcode.com/problems/assign-cookies/", topic_tags: ["Greedy Algorithm"] },
    { title: "Subsets II", difficulty: "Medium", url: "https://leetcode.com/problems/subsets-ii/", topic_tags: ["Recursion"] },
    { title: "Combination Sum", difficulty: "Medium", url: "https://leetcode.com/problems/combination-sum/", topic_tags: ["Recursion"] },
    { title: "Combination Sum II", difficulty: "Medium", url: "https://leetcode.com/problems/combination-sum-ii/", topic_tags: ["Recursion"] },
    { title: "Permutation Sequence", difficulty: "Hard", url: "https://leetcode.com/problems/permutation-sequence/", topic_tags: ["Recursion"] },
    { title: "Permutations", difficulty: "Medium", url: "https://leetcode.com/problems/permutations/", topic_tags: ["Recursion and Backtracking"] },
    { title: "N Queens", difficulty: "Hard", url: "https://leetcode.com/problems/n-queens/", topic_tags: ["Recursion and Backtracking"] },
    { title: "Sudoku Solver", difficulty: "Hard", url: "https://leetcode.com/problems/sudoku-solver/", topic_tags: ["Recursion and Backtracking"] },
    { title: "Single element in sorted array", difficulty: "Medium", url: "https://leetcode.com/problems/single-element-in-a-sorted-array/", topic_tags: ["Binary Search"] },
    { title: "Search in rotated sorted array", difficulty: "Medium", url: "https://leetcode.com/problems/search-in-rotated-sorted-array/", topic_tags: ["Binary Search"] },
    { title: "Median of 2 sorted arrays", difficulty: "Hard", url: "https://leetcode.com/problems/median-of-two-sorted-arrays/", topic_tags: ["Binary Search"] },
    { title: "Find Median from Data Stream", difficulty: "Hard", url: "https://leetcode.com/problems/find-median-from-data-stream/", topic_tags: ["Heaps"] },
    { title: "Top K Frequent Elements", difficulty: "Medium", url: "https://leetcode.com/problems/top-k-frequent-elements/", topic_tags: ["Heaps"] },
    { title: "Implement Stack using Queue", difficulty: "Easy", url: "https://leetcode.com/problems/implement-stack-using-queues/", topic_tags: ["Stack and Queue"] },
    { title: "Implement Queue using Stack", difficulty: "Easy", url: "https://leetcode.com/problems/implement-queue-using-stacks/", topic_tags: ["Stack and Queue"] },
    { title: "Balanced Parentheses", difficulty: "Easy", url: "https://leetcode.com/problems/valid-parentheses/", topic_tags: ["Stack and Queue"] },
    { title: "Next Greater Element", difficulty: "Medium", url: "https://leetcode.com/problems/next-greater-element-i/", topic_tags: ["Stack and Queue"] },
    { title: "LFU Cache", difficulty: "Hard", url: "https://leetcode.com/problems/lfu-cache/", topic_tags: ["Stack and Queue Part-II"] },
    { title: "Largest rectangle in a histogram", difficulty: "Hard", url: "https://leetcode.com/problems/largest-rectangle-in-histogram/", topic_tags: ["Stack and Queue Part-II"] },
    { title: "Sliding Window Maximum", difficulty: "Hard", url: "https://leetcode.com/problems/sliding-window-maximum/", topic_tags: ["Stack and Queue Part-II"] },
    { title: "Implement Min Stack", difficulty: "Easy", url: "https://leetcode.com/problems/min-stack/", topic_tags: ["Stack and Queue Part-II"] },
    { title: "Rotten Oranges", difficulty: "Medium", url: "https://leetcode.com/problems/rotting-oranges/", topic_tags: ["Stack and Queue Part-II"] },
    { title: "Stock span problem", difficulty: "Medium", url: "https://leetcode.com/problems/online-stock-span/", topic_tags: ["Stack and Queue Part-II"] },
    { title: "Reverse words in a string", difficulty: "Medium", url: "https://leetcode.com/problems/reverse-words-in-a-string/", topic_tags: ["String"] },
    { title: "Longest Palindrome in a string", difficulty: "Medium", url: "https://leetcode.com/problems/longest-palindromic-substring/", topic_tags: ["String"] },
    { title: "Roman to Integer", difficulty: "Easy", url: "https://leetcode.com/problems/roman-to-integer/", topic_tags: ["String"] },
    { title: "ATOI", difficulty: "Medium", url: "https://leetcode.com/problems/string-to-integer-atoi/", topic_tags: ["String"] },
    { title: "Longest Common Prefix", difficulty: "Easy", url: "https://leetcode.com/problems/longest-common-prefix/", topic_tags: ["String"] },
    { title: "Minimum insertions for palindrome", difficulty: "Hard", url: "https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/", topic_tags: ["String Part-II"] },
    { title: "Valid Anagram", difficulty: "Easy", url: "https://leetcode.com/problems/valid-anagram/", topic_tags: ["String Part-II"] },
    { title: "Count and say", difficulty: "Medium", url: "https://leetcode.com/problems/count-and-say/", topic_tags: ["String Part-II"] },
    { title: "Compare version numbers", difficulty: "Medium", url: "https://leetcode.com/problems/compare-version-numbers/", topic_tags: ["String Part-II"] },
    { title: "Inorder Traversal", difficulty: "Easy", url: "https://leetcode.com/problems/binary-tree-inorder-traversal/", topic_tags: ["Binary Tree"] },
    { title: "Preorder Traversal", difficulty: "Easy", url: "https://leetcode.com/problems/binary-tree-preorder-traversal/", topic_tags: ["Binary Tree"] },
    { title: "Postorder Traversal", difficulty: "Easy", url: "https://leetcode.com/problems/binary-tree-postorder-traversal/", topic_tags: ["Binary Tree"] },
    { title: "Right/Left View of BT", difficulty: "Medium", url: "https://leetcode.com/problems/binary-tree-right-side-view/", topic_tags: ["Binary Tree"] },
    { title: "Vertical Order Traversal", difficulty: "Hard", url: "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/", topic_tags: ["Binary Tree"] },
    { title: "Maximum Width of BT", difficulty: "Medium", url: "https://leetcode.com/problems/maximum-width-of-binary-tree/", topic_tags: ["Binary Tree"] },
    { title: "Level Order Traversal", difficulty: "Medium", url: "https://leetcode.com/problems/binary-tree-level-order-traversal/", topic_tags: ["Binary Tree part-II"] },
    { title: "Maximum Depth in BT", difficulty: "Easy", url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/", topic_tags: ["Binary Tree part-II"] },
    { title: "Diameter of Binary Tree", difficulty: "Easy", url: "https://leetcode.com/problems/diameter-of-binary-tree/", topic_tags: ["Binary Tree part-II"] },
    { title: "Check for balanced binary tree", difficulty: "Easy", url: "https://leetcode.com/problems/balanced-binary-tree/", topic_tags: ["Binary Tree part-II"] },
    { title: "LCA in BT", difficulty: "Medium", url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/", topic_tags: ["Binary Tree part-II"] },
    { title: "Same Tree", difficulty: "Easy", url: "https://leetcode.com/problems/same-tree/", topic_tags: ["Binary Tree part-II"] },
    { title: "Zig Zag Traversal", difficulty: "Medium", url: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/", topic_tags: ["Binary Tree part-II"] },
    { title: "Binary Tree Maximum Path Sum", difficulty: "Hard", url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/", topic_tags: ["Binary Tree part-III"] },
    { title: "BT from Preorder and Inorder", difficulty: "Medium", url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/", topic_tags: ["Binary Tree part-III"] },
    { title: "BT from Inorder and Postorder", difficulty: "Medium", url: "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/", topic_tags: ["Binary Tree part-III"] },
    { title: "Symmetric Tree", difficulty: "Easy", url: "https://leetcode.com/problems/symmetric-tree/", topic_tags: ["Binary Tree part-III"] },
    { title: "Flatten BT to Linked List", difficulty: "Medium", url: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/", topic_tags: ["Binary Tree part-III"] },
    { title: "Populating Next Right Pointers", difficulty: "Medium", url: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/", topic_tags: ["Binary Search Tree"] },
    { title: "Search in BST", difficulty: "Easy", url: "https://leetcode.com/problems/search-in-a-binary-search-tree/", topic_tags: ["Binary Search Tree"] },
    { title: "BST from sorted array", difficulty: "Easy", url: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/", topic_tags: ["Binary Search Tree"] },
    { title: "BST from preorder", difficulty: "Medium", url: "https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/", topic_tags: ["Binary Search Tree"] },
    { title: "Validate BST", difficulty: "Medium", url: "https://leetcode.com/problems/validate-binary-search-tree/", topic_tags: ["Binary Search Tree"] },
    { title: "LCA in BST", difficulty: "Medium", url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", topic_tags: ["Binary Search Tree"] },
    { title: "Kth smallest element in BST", difficulty: "Medium", url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", topic_tags: ["Binary Search Tree Part-II"] },
    { title: "Two sum in BST", difficulty: "Easy", url: "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/", topic_tags: ["Binary Search Tree Part-II"] },
    { title: "BST iterator", difficulty: "Medium", url: "https://leetcode.com/problems/binary-search-tree-iterator/", topic_tags: ["Binary Search Tree Part-II"] },
    { title: "Largest BST in Binary Tree", difficulty: "Hard", url: "https://leetcode.com/problems/maximum-sum-bst-in-binary-tree/", topic_tags: ["Binary Search Tree Part-II"] },
    { title: "Serialize and Deserialize BT", difficulty: "Hard", url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", topic_tags: ["Binary Search Tree Part-II"] },
    { title: "Flood-fill Algorithm", difficulty: "Easy", url: "https://leetcode.com/problems/flood-fill/", topic_tags: ["Binary Trees[Misc]"] },
    { title: "Clone Graph", difficulty: "Medium", url: "https://leetcode.com/problems/clone-graph/", topic_tags: ["Graph"] },
    { title: "Course Schedule", difficulty: "Medium", url: "https://leetcode.com/problems/course-schedule/", topic_tags: ["Graph"] },
    { title: "Number of Islands", difficulty: "Medium", url: "https://leetcode.com/problems/number-of-islands/", topic_tags: ["Graph"] },
    { title: "Bipartite Graph", difficulty: "Medium", url: "https://leetcode.com/problems/is-graph-bipartite/", topic_tags: ["Graph"] },
    { title: "Max Product Subarray", difficulty: "Medium", url: "https://leetcode.com/problems/maximum-product-subarray/", topic_tags: ["Dynamic Programming"] },
    { title: "Edit Distance", difficulty: "Hard", url: "https://leetcode.com/problems/edit-distance/", topic_tags: ["Dynamic Programming"] },
    { title: "Minimum Path Sum", difficulty: "Medium", url: "https://leetcode.com/problems/minimum-path-sum/", topic_tags: ["DP Part-II"] },
    { title: "Coin Change 2", difficulty: "Medium", url: "https://leetcode.com/problems/coin-change-2/", topic_tags: ["DP Part-II"] },
    { title: "Trie Implementation", difficulty: "Medium", url: "https://leetcode.com/problems/implement-trie-prefix-tree/", topic_tags: ["Trie"] },
    { title: "Maximum XOR of two numbers", difficulty: "Medium", url: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/", topic_tags: ["Trie"] },
    { title: "Maximum XOR with an element", difficulty: "Hard", url: "https://leetcode.com/problems/maximum-xor-with-an-element-from-array/", topic_tags: ["Trie"] }
];
