ALTER TABLE public.user_bookmarks
  ADD COLUMN IF NOT EXISTS last_reviewed TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS review_interval INTEGER DEFAULT 1,
  ADD COLUMN IF NOT EXISTS ease_factor NUMERIC DEFAULT 2.5,
  ADD COLUMN IF NOT EXISTS next_review TIMESTAMPTZ DEFAULT now();
