-- Migration: Dream 50 Seeding
-- Seeding the high-priority targets requested by the command center.

INSERT INTO companies (name, slug, description, hq, industry, tier) VALUES
('Celebal Technologies', 'celebal-technologies', 'Leading software services company specializing in AI, Big Data, and Enterprise Cloud.', 'Jaipur, India', 'Technology', 'free'),
('FreeCharge', 'freecharge', 'Digital marketplace for financial services and payments.', 'Gurugram, India', 'Fintech', 'free'),
('Provakil', 'provakil', 'Legal operations and management software for enterprises.', 'New Delhi, India', 'LegalTech', 'free'),
('ShodhAI', 'shodhai', 'Advanced AI-driven research and analysis platform.', 'Bengaluru, India', 'Technology', 'free'),
('Unicommerce', 'unicommerce', 'E-commerce supply chain solution provided for multi-channel selling.', 'Gurugram, India', 'E-commerce', 'free'),
('Nagarro Software', 'nagarro-software', 'Global digital engineering leader with a focus on agility.', 'Gurugram, India', 'IT Services', 'free'),
('TITAN.email', 'titan-email', 'Professional email suite designed for small businesses.', 'Mumbai, India', 'SaaS', 'free'),
('Treebo Hotels', 'treebo-hotels', 'Tech-enabled budget hotel chain with high operational efficiency.', 'Bengaluru, India', 'Hospitality', 'free'),
('Spring Financial', 'spring-financial', 'Financial services platform with a focus on credit building.', 'Vancouver, Canada', 'Fintech', 'free'),
('APMSE (Eagleview)', 'apmse-eagleview', 'Aerial imagery and data analytics for property insights.', 'Bellevue, WA', 'PropertyTech', 'free'),
('ZS Associates', 'zs-associates', 'Management consulting and technology firm focused on healthcare.', 'Evanston, IL', 'Consulting', 'free'),
('DEShaw', 'deshaw', 'Global investment and technology development firm.', 'New York, NY', 'Fintech', 'pro'),
('EPAM', 'epam', 'Leading digital transformation services and product engineering.', 'Newtown, PA', 'IT Services', 'free'),
('ProcDNA', 'procdna', 'Pharma-focused data and analytics consulting firm.', 'Bengaluru, India', 'Consulting', 'free'),
('Media.net', 'media-net', 'Global advertising technology company.', 'Dubai, UAE', 'AdTech', 'pro'),
('Triology', 'triology', 'Strategic software development and consulting.', 'Pune, India', 'Technology', 'free'),
('E2E Networks', 'e2e-networks', 'Cloud infrastructure provider focused on high-performance computing.', 'New Delhi, India', 'Technology', 'free'),
('Tekion', 'tekion', 'Cloud-native automotive retail platform.', 'Pleasanton, CA', 'Automotive', 'free'),
('Signzy', 'signzy', 'AI-powered identity verification and banking automation.', 'Bengaluru, India', 'Fintech', 'free'),
('Whatfix (Quiko)', 'whatfix', 'Digital adoption platform for enterprise software.', 'Bengaluru, India', 'SaaS', 'free'),
('Eatclub', 'eatclub', 'Tech-first food delivery and cloud kitchen platform.', 'Mumbai, India', 'FoodTech', 'free'),
('MakeMyTrip', 'makemytrip', 'India''s largest online travel company.', 'Gurugram, India', 'TravelTech', 'free'),
('Sprinklr', 'sprinklr', 'Customer experience management platform for enterprises.', 'New York, NY', 'SaaS', 'pro'),
('Addverb Technologies', 'addverb-technologies', 'Leading robotics and automation solutions company.', 'Noida, India', 'Robotics', 'free'),
('Triumph Motorcycles', 'triumph-motorcycles', 'Iconic British motorcycle manufacturer.', 'Hinckley, UK', 'Automotive', 'free'),
('Bajaj Finserv Health Limited', 'bajaj-finserv-health', 'Health-tech initiative focusing on decentralized care.', 'Pune, India', 'HealthTech', 'free'),
('BNY Mellon', 'bny-mellon', 'Global investment company providing financial services.', 'New York, NY', 'Fintech', 'pro'),
('Deloitte', 'deloitte', 'Multinational professional services network.', 'London, UK', 'Consulting', 'free'),
('OneBanc', 'onebanc', 'AI-driven banking solution for enterprises and individuals.', 'Gurugram, India', 'Fintech', 'free'),
('Curiflow', 'curiflow', 'Precision healthcare and data flow management.', 'Bengaluru, India', 'HealthTech', 'free'),
('Aperam', 'aperam', 'Global player in stainless, electrical and specialty steel.', 'Luxembourg', 'Manufacturing', 'free'),
('AMD', 'amd', 'Global semiconductor company specializing in processors.', 'Santa Clara, CA', 'Hardware', 'pro'),
('GoDaddy', 'godaddy', 'Global domain registrar and web hosting company.', 'Tempe, AZ', 'Web Services', 'free'),
('HSBC', 'hsbc', 'One of the largest banking and financial institutions.', 'London, UK', 'Fintech', 'free'),
('Samsung Noida', 'samsung-noida', 'Largest mobile manufacturing unit of Samsung globally.', 'Noida, India', 'Electronics', 'free'),
('Josh Technology Group', 'josh-technology-group', 'Niche product engineering firm focusing on tech excellence.', 'Gurugram, India', 'Technology', 'free'),
('Park+ (Parviom Technologies)', 'park-plus', 'Smart parking and car ownership super app.', 'Gurugram, India', 'Automotive', 'free'),
('Eucloid', 'eucloid', 'Data and marketing analytics consulting firm.', 'Gurugram, India', 'Consulting', 'free'),
('ION', 'ion', 'Financial software and data provider.', 'Dublin, Ireland', 'Fintech', 'free'),
('rtCamp', 'rtcamp', 'WordPress-focused web agency and enterprise solutions.', 'Pune, India', 'MediaTech', 'free'),
('Honda Cars', 'honda-cars', 'Leading automobile manufacturer with high-tech focus.', 'Greater Noida, India', 'Automotive', 'free')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  industry = EXCLUDED.industry;
